name = "redbullapplication"
main = "worker/index.js"
compatibility_date = "2026-06-13"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "redbull_tracking"
database_id = "6e6064d2-ddfb-4ca1-84e4-f214ac07e63c"
